/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as DaemonsIndexRouteImport } from './routes/daemons/index'
import { Route as DaemonsDaemonIdRouteImport } from './routes/daemons/$daemonId'
import { Route as DeviceIndexRouteImport } from './routes/device/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows/index'
import { Route as WorkflowsWorkflowIdRouteImport } from './routes/workflows/$workflowId'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as ProjectsProjectIdSettingsRouteImport } from './routes/projects/$projectId/settings'
import { Route as WorkflowsWorkflowIdIndexRouteImport } from './routes/workflows/$workflowId/index'
import { Route as WorkflowsWorkflowIdEditRouteImport } from './routes/workflows/$workflowId/edit'
import { Route as ProjectsProjectIdRunsRunIdRouteImport } from './routes/projects/$projectId/runs/$runId'
import { Route as ProjectsProjectIdRunsNewRouteImport } from './routes/projects/$projectId/runs/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const DaemonsIndexRoute = DaemonsIndexRouteImport.update({
  id: '/daemons/',
  path: '/daemons/',
  getParentRoute: () => rootRouteImport,
} as any)
const DaemonsDaemonIdRoute = DaemonsDaemonIdRouteImport.update({
  id: '/daemons/$daemonId',
  path: '/daemons/$daemonId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceIndexRoute = DeviceIndexRouteImport.update({
  id: '/device/',
  path: '/device/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsWorkflowIdRoute = WorkflowsWorkflowIdRouteImport.update({
  id: '/workflows/$workflowId',
  path: '/workflows/$workflowId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdSettingsRoute =
  ProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const WorkflowsWorkflowIdIndexRoute =
  WorkflowsWorkflowIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkflowsWorkflowIdRoute,
  } as any)
const WorkflowsWorkflowIdEditRoute = WorkflowsWorkflowIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => WorkflowsWorkflowIdRoute,
} as any)
const ProjectsProjectIdRunsRunIdRoute =
  ProjectsProjectIdRunsRunIdRouteImport.update({
    id: '/runs/$runId',
    path: '/runs/$runId',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdRunsNewRoute =
  ProjectsProjectIdRunsNewRouteImport.update({
    id: '/runs/new',
    path: '/runs/new',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/daemons/$daemonId': typeof DaemonsDaemonIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRouteWithChildren
  '/daemons/': typeof DaemonsIndexRoute
  '/device/': typeof DeviceIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/workflows/$workflowId/edit': typeof WorkflowsWorkflowIdEditRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/workflows/$workflowId/': typeof WorkflowsWorkflowIdIndexRoute
  '/projects/$projectId/runs/$runId': typeof ProjectsProjectIdRunsRunIdRoute
  '/projects/$projectId/runs/new': typeof ProjectsProjectIdRunsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/daemons/$daemonId': typeof DaemonsDaemonIdRoute
  '/daemons': typeof DaemonsIndexRoute
  '/device': typeof DeviceIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/workflows/$workflowId/edit': typeof WorkflowsWorkflowIdEditRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdIndexRoute
  '/projects/$projectId/runs/$runId': typeof ProjectsProjectIdRunsRunIdRoute
  '/projects/$projectId/runs/new': typeof ProjectsProjectIdRunsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/daemons/$daemonId': typeof DaemonsDaemonIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRouteWithChildren
  '/daemons/': typeof DaemonsIndexRoute
  '/device/': typeof DeviceIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/workflows/$workflowId/edit': typeof WorkflowsWorkflowIdEditRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/workflows/$workflowId/': typeof WorkflowsWorkflowIdIndexRoute
  '/projects/$projectId/runs/$runId': typeof ProjectsProjectIdRunsRunIdRoute
  '/projects/$projectId/runs/new': typeof ProjectsProjectIdRunsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/daemons/$daemonId'
    | '/projects/$projectId'
    | '/workflows/$workflowId'
    | '/daemons/'
    | '/device/'
    | '/projects/'
    | '/workflows/'
    | '/projects/$projectId/settings'
    | '/workflows/$workflowId/edit'
    | '/projects/$projectId/'
    | '/workflows/$workflowId/'
    | '/projects/$projectId/runs/$runId'
    | '/projects/$projectId/runs/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/daemons/$daemonId'
    | '/daemons'
    | '/device'
    | '/projects'
    | '/workflows'
    | '/projects/$projectId/settings'
    | '/workflows/$workflowId/edit'
    | '/projects/$projectId'
    | '/workflows/$workflowId'
    | '/projects/$projectId/runs/$runId'
    | '/projects/$projectId/runs/new'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/daemons/$daemonId'
    | '/projects/$projectId'
    | '/workflows/$workflowId'
    | '/daemons/'
    | '/device/'
    | '/projects/'
    | '/workflows/'
    | '/projects/$projectId/settings'
    | '/workflows/$workflowId/edit'
    | '/projects/$projectId/'
    | '/workflows/$workflowId/'
    | '/projects/$projectId/runs/$runId'
    | '/projects/$projectId/runs/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  DaemonsDaemonIdRoute: typeof DaemonsDaemonIdRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  WorkflowsWorkflowIdRoute: typeof WorkflowsWorkflowIdRouteWithChildren
  DaemonsIndexRoute: typeof DaemonsIndexRoute
  DeviceIndexRoute: typeof DeviceIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daemons/': {
      id: '/daemons/'
      path: '/daemons'
      fullPath: '/daemons/'
      preLoaderRoute: typeof DaemonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daemons/$daemonId': {
      id: '/daemons/$daemonId'
      path: '/daemons/$daemonId'
      fullPath: '/daemons/$daemonId'
      preLoaderRoute: typeof DaemonsDaemonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device/': {
      id: '/device/'
      path: '/device'
      fullPath: '/device/'
      preLoaderRoute: typeof DeviceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$workflowId': {
      id: '/workflows/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof WorkflowsWorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/settings': {
      id: '/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/workflows/$workflowId/': {
      id: '/workflows/$workflowId/'
      path: '/'
      fullPath: '/workflows/$workflowId/'
      preLoaderRoute: typeof WorkflowsWorkflowIdIndexRouteImport
      parentRoute: typeof WorkflowsWorkflowIdRoute
    }
    '/workflows/$workflowId/edit': {
      id: '/workflows/$workflowId/edit'
      path: '/edit'
      fullPath: '/workflows/$workflowId/edit'
      preLoaderRoute: typeof WorkflowsWorkflowIdEditRouteImport
      parentRoute: typeof WorkflowsWorkflowIdRoute
    }
    '/projects/$projectId/runs/$runId': {
      id: '/projects/$projectId/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/projects/$projectId/runs/$runId'
      preLoaderRoute: typeof ProjectsProjectIdRunsRunIdRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/runs/new': {
      id: '/projects/$projectId/runs/new'
      path: '/runs/new'
      fullPath: '/projects/$projectId/runs/new'
      preLoaderRoute: typeof ProjectsProjectIdRunsNewRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdSettingsRoute: typeof ProjectsProjectIdSettingsRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  ProjectsProjectIdRunsRunIdRoute: typeof ProjectsProjectIdRunsRunIdRoute
  ProjectsProjectIdRunsNewRoute: typeof ProjectsProjectIdRunsNewRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdSettingsRoute: ProjectsProjectIdSettingsRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  ProjectsProjectIdRunsRunIdRoute: ProjectsProjectIdRunsRunIdRoute,
  ProjectsProjectIdRunsNewRoute: ProjectsProjectIdRunsNewRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

interface WorkflowsWorkflowIdRouteChildren {
  WorkflowsWorkflowIdEditRoute: typeof WorkflowsWorkflowIdEditRoute
  WorkflowsWorkflowIdIndexRoute: typeof WorkflowsWorkflowIdIndexRoute
}

const WorkflowsWorkflowIdRouteChildren: WorkflowsWorkflowIdRouteChildren = {
  WorkflowsWorkflowIdEditRoute: WorkflowsWorkflowIdEditRoute,
  WorkflowsWorkflowIdIndexRoute: WorkflowsWorkflowIdIndexRoute,
}

const WorkflowsWorkflowIdRouteWithChildren =
  WorkflowsWorkflowIdRoute._addFileChildren(WorkflowsWorkflowIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  DaemonsDaemonIdRoute: DaemonsDaemonIdRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  WorkflowsWorkflowIdRoute: WorkflowsWorkflowIdRouteWithChildren,
  DaemonsIndexRoute: DaemonsIndexRoute,
  DeviceIndexRoute: DeviceIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
